In [3]:
## loading the datasets
import pandas as pd

movies = pd.read_csv(r"C:\Users\shivraj\OneDrive\Desktop\ML PROJECTS\Movie recommendation system\tmdb_5000_movies.csv")
credits = pd.read_csv(r"C:\Users\shivraj\OneDrive\Desktop\ML PROJECTS\Movie recommendation system\tmdb_5000_credits.csv")

print(movies.shape)
print(credits.shape)

(4803, 20)
(4803, 4)

In [6]:
print("\nMovie columns:")
print(movies.columns.tolist())

print("\nCredits columns:")
print(credits.columns.tolist())

Movie columns:
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count']

Credits columns:
['movie_id', 'title', 'cast', 'crew']

In [7]:
### Merging the two datasets

movies = movies.merge(
    credits,
    left_on='id',
    right_on='movie_id'
)

print(movies.shape)

(4803, 24)

In [11]:
movies = movies[
    ['movie_id', 'title_x', 'genres', 'keywords', 'overview', 'cast', 'crew']
]

# Rename title_x to title
movies.rename(columns={'title_x': 'title'}, inplace=True)

print(movies.shape)
movies.head()

(4803, 7)

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
movies[['genres', 'keywords', 'cast', 'crew']].head(1)

,genres,keywords,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [13]:
## converting json like columns into python data

import ast

movies['genres'] = movies['genres'].apply(ast.literal_eval)
movies['keywords'] = movies['keywords'].apply(ast.literal_eval)
movies['cast'] = movies['cast'].apply(ast.literal_eval)
movies['crew'] = movies['crew'].apply(ast.literal_eval)

movies[['genres', 'keywords', 'cast', 'crew']].head(1)

,genres,keywords,cast,crew
0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 1463, 'name': 'culture clash'}, {'id':...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."

In [14]:
def get_names(data):
    return [item['name'] for item in data]

movies['genres'] = movies['genres'].apply(get_names)

movies[['title', 'genres']].head()

,title,genres
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]"
2,Spectre,"[Action, Adventure, Crime]"
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]"
4,John Carter,"[Action, Adventure, Science Fiction]"

In [15]:
movies['keywords'] = movies['keywords'].apply(get_names)

movies[['title', 'keywords']].head()

,title,keywords
0,Avatar,"[culture clash, future, space war, space colon..."
1,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ..."
2,Spectre,"[spy, based on novel, secret agent, sequel, mi..."
3,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i..."
4,John Carter,"[based on novel, mars, medallion, space travel..."

In [16]:
def get_cast_names(data):
    return [item['name'] for item in data[:3]]

movies['cast'] = movies['cast'].apply(get_cast_names)

movies[['title', 'cast']].head()

,title,cast
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]"
3,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]"
4,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]"

In [18]:
def get_director(data):
    for item in data:
        if item['job'] == 'Director':
            return item['name']
    return ''

movies['director'] = movies['crew'].apply(get_director)

movies[['title', 'director']].head()

                                      title           director
0                                    Avatar      James Cameron
1  Pirates of the Caribbean: At World's End     Gore Verbinski
2                                   Spectre         Sam Mendes
3                     The Dark Knight Rises  Christopher Nolan
4                               John Carter     Andrew Stanton

In [20]:
#creating a movie tag
movies['overview'] = movies['overview'].fillna('')

movies['tags'] = (
    movies['genres'] +
    movies['keywords'] +
    movies['cast'] +
    movies['director'].apply(lambda x: [x]) +
    movies['overview'].apply(lambda x: [x])
)

movies[['title', 'tags']].head()

,title,tags
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction, ..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drug abuse..."
2,Spectre,"[Action, Adventure, Crime, spy, based on novel..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dc comics, cr..."
4,John Carter,"[Action, Adventure, Science Fiction, based on ..."

In [21]:
##converting tags from a list to a string
movies['tags'] = movies['tags'].apply(lambda x: ' '.join(x))

movies[['title', 'tags']].head()

,title,tags
0,Avatar,Action Adventure Fantasy Science Fiction cultu...
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...
2,Spectre,Action Adventure Crime spy based on novel secr...
3,The Dark Knight Rises,Action Crime Drama Thriller dc comics crime fi...
4,John Carter,Action Adventure Science Fiction based on nove...

In [22]:
##using TF-IDF vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000, stop_words='english')

tfidf_matrix = tfidf.fit_transform(movies['tags'])

print(tfidf_matrix.shape)

(4803, 5000)

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(tfidf_matrix)

print(similarity.shape)

(4803, 4803)

In [24]:
print(movies['title'].iloc[0])
print(movies['title'].iloc[1])

print(similarity[0][1])

Avatar
Pirates of the Caribbean: At World's End
0.0215039752094495

In [25]:
def recommend_movies(movie_title):
    movie_index = movies[movies['title'] == movie_title].index[0]

    similarity_scores = similarity[movie_index]

    similar_movies = sorted(
        list(enumerate(similarity_scores)),
        key=lambda x: x[1],
        reverse=True
    )

    for i in similar_movies[1:6]:
        print(movies.iloc[i[0]]['title'])

In [26]:
recommend_movies('Avatar')

Aliens
Alien
Moonraker
Alien³
Silent Running